version: '2'
services:
    web:
        image: hitalos/laravel
        stdin_open: true
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
        links:
            - search
    search:
        image: elasticsearch
        ports:
            - 9200:9200
